name: CI
on:
  push:
jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -ll -ii -r . -f json -o ci_report.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-finding
          path: ci_report.json

  image_scan:
    name: Build and Run Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '20.10.7'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REPO_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build Image
        run: docker build -f Dockerfile -t myapp:latest .
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: quickview,cves
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
